### PR TITLE
Glusterfs Template:Read only boolean value added as string

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
Closes: #83 
Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/80)

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
This was causing error in the deployment of gluster template.

**Comment by jarrpa** [comment]
Conflicted with #74. Does it still apply in the YAML?

**Comment by MohamedAshiqrh** [comment]
@jarrpa Will look at it.

**Comment by MohamedAshiqrh** [comment]
Closing this as it is not valid anymore. created changes for yaml #89 .

**Pull request closed without merging**
