### PR TITLE
TEST PR - DO NOT MERGE 

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
changed with default value as false
Signed-off-by: Saravanakumar <sarumuga@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/448)

### CODE REVIEW

**Comment by jarrpa** [comment]
Are you running these tests locally as well?

**Comment by SaravanaStorageNetwork** [comment]
@jarrpa  verified the steps locally - works fine. 
I wonder anything to do "TRUE" as value in heketi deployment - So trying this PR just to confirm.

**Comment by SaravanaStorageNetwork** [comment]
@jarrpa  please refer https://github.com/gluster/gluster-kubernetes/pull/447#issuecomment-370470290

please issue test this pr - let us see.

**Comment by jarrpa** [comment]
Hmm.... I wonder if it might have been a fluke that it passed.

retest this please

**Comment by jarrpa** [comment]
retest this please

**Comment by obnoxxx** [comment]
Also see #449 for a PR that does not change code / templates at all...

**Comment by jarrpa** [comment]
As the test is done, closing this PR.

**Pull request closed without merging**
