### PR TITLE
Print all output to log file

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/178)

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
@humblec @raghavendra-talur @ramkrsna @jarrpa @obnoxxx Please Review.

**Comment by humblec** [comment]
LGTM.  iic, @jarrpa agreed on this, so merging it for now.

**Comment by jarrpa** [comment]
I agreed that this needed solving, I don't agree with this solution.

**Comment by humblec** [comment]
@jarrpa its my mistake. I misinterpreted it.  We will work on it soon.

**Pull request merged**
