### PR TITLE
vagrant: give firewalld rules names for easier stepping/tracking

### PR DESCRIPTION
**Pull request by obnoxxx**
Signed-off-by: Michael Adam <obnox@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/224)

### CODE REVIEW

**Comment by jarrpa** [comment]
Would it make sense to give the tasks more descriptive names? Like "firewall: Make eth1 trusted" or "firewall: Trust Weave Net CIDR"?

**Comment by obnoxxx** [comment]
@jarrpa yeah, that makes sense. i'll update...

**Comment by obnoxxx** [comment]
@jarrpa updated. does that look better?

Also rebased and added a patch to remove the redundant comments...

**Comment by jarrpa** [comment]
LGTM

**Pull request merged**
