### PR TITLE
README: improve formatting

### PR DESCRIPTION
**Pull request by obnoxxx**
Don't use both bold and italics, but just one.

Signed-off-by: Michael Adam <obnox@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/449)

### CODE REVIEW

**Comment by obnoxxx** [comment]
It's outlawed in typesetting to use both bold and italics at the same time. Let's not do it here.

**Comment by jarrpa** [comment]
What does "outlawed in typesetting" mean? Is it not valid markdown?

**Comment by obnoxxx** [comment]
@jarrpa wrote:
> What does "outlawed in typesetting" mean? Is it not valid markdown?

Nothing to do with markdown. I mean that using bold + italic is frowned upon as bad taste,

**Comment by jarrpa** [comment]
Huh... I'll file that along with "two spaces after every period". ;) But sure, it's fine. Let's see how the CI behaves...

**Comment by obnoxxx** [comment]
oh. this passed!

**Comment by jarrpa** [comment]
Yup, restarted testing on the problematic PR. merging!

**Comment by obnoxxx** [comment]
@jarrpa yeah. I just wanted to propose a change that is not touching code and is genuine enough to qualify for merging if tests pass. But the main purpose was testing the CI run...

**Pull request merged**
