### PR TITLE
switching to yaml format

### LINKED ISSUE #64: discussion: convert json to yaml
Wondering if we should convert json to yaml, I believe OpenShift and Kube have settled on yaml as the official object spec def.

What say you @obnoxxx @jarrpa @wattsteve @erinboyd

I can do the conversion if everyone is in agreement

### PR DESCRIPTION
**Pull request by screeley44**
fixes #64 

I archived the json for now, and tested with kube.  I left the topology as json as there are strict instructions on the heketi site that you `MUST` use json 

```
[root@master deploy]# kubectl get pods
NAME                     READY     STATUS    RESTARTS   AGE
glusterfs-0c818          1/1       Running   0          3m
glusterfs-d5uq6          1/1       Running   0          3m
glusterfs-xfw8u          1/1       Running   0          3m
heketi-898148926-rdz42   1/1       Running   0          1m
```

@jarrpa  PTAL

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/74)

### CODE REVIEW

**Comment by jarrpa** [comment]
Initial pass looks good. I'll look at it again a bit later and run it through my own sanity testing.

We can probably do without the archive directory entirely, the files will always persist in git. :)

**Comment by screeley44** [comment]
true, I will remove the archive directory

**Comment by humblec** [comment]
@screeley44 Thanks for this PR! LGTM

**Comment by jarrpa** [comment]
Tested, works for me! Merging.

**Pull request merged**
