### PR TITLE
Fix selector in heketi OCP template.

### LINKED ISSUE #197: Error in deployment config heketi
invalid value while creating Deployment config Heketi.

[root@master1 deploy]# oc process heketi | oc create -f  - 
secret "heketi-db-backup" created
service "heketi" created
route "heketi" created
The DeploymentConfig "heketi" is invalid: spec.template.metadata.labels: Invalid value: {"glusterfs":"heketi-pod"}: `selector` does not match template `labels`
[root@master1 deploy]# 

This patch (provided by Ashiq) helped:

--- a/deploy/ocp-templates/heketi-template.yaml
+++ b/deploy/ocp-templates/heketi-template.yaml
@@ -56,7 +56,7 @@ objects:
   spec:
     replicas: 1
     selector:
---      name: heketi
+++      glusterfs: heketi-pod

### PR DESCRIPTION
**Pull request by jarrpa**
Fixes #197.

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/199)

### CODE REVIEW

**Comment by obnoxxx** [comment]
Thanks @jarrpa . So is the kube-template not broken? (Just asking because #191 changed both).

**Comment by jarrpa** [comment]
Doesn't seem like it. I don't see a `selector` field there, must be something exclusive to DeploymentConfigs. Also it worked when I tested it after my last PR.

**Comment by obnoxxx** [comment]
https://github.com/gluster/gluster-kubernetes/pull/191/commits/50978ebe91e5126b2fd93021d20e26b589fc524a changed a selector in kube-templates as well, hence asking... But if you tested it, I'm fine. :-)

**Comment by obnoxxx** [comment]
after more discussions and analysis ... LGTM

**Pull request merged**
