### PR TITLE
Abort should not be called on heketi failure

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/206)

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
Abort at this point is just too much mess. topology load again happens will fail. also heketi deployment will fail as it will not find the endpoint.

**Comment by jarrpa** [comment]
Okay... the code looks good. If you could add the comment you just made into the commit message I'll merge it. :)

**Comment by jarrpa** [comment]
Also mention that aborting at this point is incomplete as the devices are already formatted.

**Comment by MohamedAshiqrh** [comment]
@jarrpa added it to commit

**Comment by jarrpa** [comment]
LGTM

**Pull request merged**
