### PR TITLE
Namespace to error if any similar name with -

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
Closes: #126 
Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/134)

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
Currently if there is a name with - grep accepts it. like if there is storage-namespace and namespace option is given as storage grep accepts storage as valid namespace. This patch will stop this behavior.

**Comment by MohamedAshiqrh** [comment]
```
# oc get namespace | grep -w infra
management-infra   Active    3d
openshift-infra    Active    3d
```

**Comment by MohamedAshiqrh** [comment]
# oc get namespace | grep  <\infra\>
-bash: infra>: No such file or directory

**Comment by MohamedAshiqrh** [comment]
Please review @raghavendra-talur @humblec @jarrpa

**Comment by humblec** [comment]
LGTM. This looks to be the correct way, instead of grep foo. merging..

**Pull request merged**
