### PR TITLE
Using port forward

### PR DESCRIPTION
**Pull request by FaKod**
Changes:

1. I do not know, how you expect to access the deploy-heketi endpoint by this script. IMHO a port-forward to the heketi-pod is one solution for _stock_ Kubernetes (querying for free local port is missing...)
2. I had some remaining k8s objects, depending on if the NS is the current context or as cmd line parameter to the script
3. I think node label overwrite is valid here (had some errrors on script restart, if abort() wasn't called before)

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/265)

### CODE REVIEW

**Comment by FaKod** [comment]
Hi @jarrpa, just out of interest, from where do you execute the script gk-deploy from?

**Comment by jarrpa** [comment]
@FaKod Myself, I work primarily in VM environments. I run the gk-deploy script from a VM, either in or outside the kube cluster, that can access the cluster via kubectl.

**Comment by FaKod** [comment]
ok, then I do not understand how you access your svc/heketi endpoints from outside the cluster (by gk-deploy).

Anyway, it's only for testing pods existence. 
So I close this PR now.

**Comment by jarrpa** [comment]
@FaKod I deploy weave-net to facilitate my cluster networking. It allows the service to have an IP address accessible from outside the cluster.

**Pull request closed without merging**
