### PR TITLE
gk-deploy: fix heketi.json for heketi-HA

### PR DESCRIPTION
**Pull request by jarrpa**
Missed a key configuration parameter.

Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/297)

### CODE REVIEW

**Comment by obnoxxx** [comment]
why is this a pr of its own and also part of pr #289 ?

**Comment by jarrpa** [comment]
....not really sure. I think I was just tired this morning when I found the bug. ;)

**Comment by obnoxxx** [comment]
so this is a fix of something introduced earlier, not of something introduced in the idempotency pr, right?

**Comment by jarrpa** [comment]
Oh, yes, it was introduced in #281

**Comment by obnoxxx** [comment]
LGTM

**Pull request merged**
