### PR TITLE
Add a streamlined deploy option through ansible

### PR DESCRIPTION
**Pull request by ravishivt**
This implements #149.  It creates a new ansible/ directory with ansible playbooks and roles to deploy the project to a pre-existing cluster.  The user needs to still specify the ansible inventory file and the topology.json file.  The new ansible option does not supersede the existing manual deployment procedure or documentation.  An initial README is added with details on what the playbooks and roles do and how to use them.

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/155)

### CODE REVIEW

**Comment by jarrpa** [comment]
I want to do a careful review of this and test it out myself, so it may take me a bit. But I like it thus far!

**Comment by jarrpa** [comment]
@ravishivt A bit of a non-update, since I don't want you to think I'm not thinking about this:

I've been prepping for a cross-continental trip to two conferences, so my apologies for the continued delay. I'll have plenty of time on planes and a week between the conferences to try and check this out, so I hope to get some comments back to you soon.

**Comment by ravishivt** [comment]
@jarrpa No worries.  Take your time and safe travels.  One thing to note is that your ansible version must be < 2.2.x.  Ansible 2.x and after has a bug that our playbook will hit.

**Comment by jarrpa** [comment]
@ravishivt Heyo. Coming in almost a month later to say that i still haven't been able to take this for a proper test run. :( My apologies. I've been hit with deadlines downstream, but we're hoping to clear them by next week.

I have, however, been able to at least read through most of it and offhand it looks pretty solid on the Debian side. I'm currently not planning to run the Debian side through its paces, mostly because I'd rather save the time of figuring out how to bring up an Ubuntu cluster (it's been long enough as it is!).

One thing to note is that with the release of heketi version 4 I plan on going off of that version for this project rather than tracking heketi master. That work will go in to the repo before this PR does, which means I'd like this playbook to build heketi v4 rather than master. I'll update this PR when that happens, and if I'm a decent human being maybe even provide patches. :)

Again, my apologies, we really do appreciate your contributions and don't like how long we've been letting this sit idle. Hope to bring some good news soon.

**Comment by jarrpa** [comment]
@ravishivt All right, I've taken a crack at this and have some questions/comments:

1. Is there a reason I'm not seeing as to why the bootstrap and gk-prep roles couldn't be merged?
2. We should be able to specify cluster nodes and devices in the inventory.ini file and just generate a topology file.
3. I know that for `yum` at least if you specify a package that is already installed it will still succeed, just with a warning. Is `apt-get` similar? If so we don't need to check for python already existing.
4. heketi 4 has been released, so we should build that version

**Comment by goern** [comment]
I wonder if you could provide a heketi-cli container as I cant build it on an Fedora Atomic Host

**Comment by obnoxxx** [comment]
@goern how does that request/question relate to this PR?

It would certainly be possible. up to now we've never needed to build a specific cli container.

**Comment by jarrpa** [comment]
Closing this PR. It can be reopened if needed.

**Pull request closed without merging**
