### PR TITLE
fstab var contains /, hence use # delimiter

### PR DESCRIPTION
**Pull request by raghavendra-talur**
Signed-off-by: Raghavendra Talur <rtalur@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/354)

### CODE REVIEW

**Comment by humblec** [comment]
LGTM. but we will wait for @jarrpa

**Comment by jarrpa** [comment]
@raghavendra-talur Still waiting for my comments to be addressed. :)

**Comment by raghavendra-talur** [comment]
@jarrpa done, I updated the same commit.

**Comment by jarrpa** [comment]
LGTM!

**Pull request merged**
