### PR TITLE
Value is deprecated in openshift and param is the new value

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/216)

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
```

role "edit" added: "system:serviceaccount:aplo:heketi-service-account"
Flag --value has been deprecated, Use -p, --param instead.
Flag --value has been deprecated, Use -p, --param instead.
service "deploy-heketi" created
route "deploy-heketi" created
deploymentconfig "deploy-heketi" created
```

**Comment by MohamedAshiqrh** [comment]
@obnoxxx @jarrpa PTAL

**Comment by jarrpa** [comment]
LGTM

**Comment by jarrpa** [comment]
Please modify the commit message to something like `oc process: -v is deprecated, use -p instead`.

**Comment by jarrpa** [comment]
Closing since #222 addresses the requested changes.

**Pull request closed without merging**
