### PR TITLE
make namespace not required in OpenShift

### PR DESCRIPTION
**Pull request by raghavendra-talur**
Closes: #106

Signed-off-by: Raghavendra Talur <rtalur@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/120)

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
@humblec @jarrpa @obnoxxx Please don't merge this unless I comment back on it. This is still Work in Progress.

**Comment by obnoxxx** [comment]
@raghavendra-talur not merge-able anyways -- there are conflicts :-)

**Comment by jarrpa** [comment]
This is also being taken care of by PR #112.

**Comment by obnoxxx** [comment]
Since #112 is closed, am I correct in assuming this can be closed? @jarrpa  @raghavendra-talur

**Comment by humblec** [comment]
Yes, #112 take care of this. iic,  thats why @raghavendra-talur said `please wait`  in first place :)

**Comment by raghavendra-talur** [comment]
@obnoxxx @jarrpa @humblec Yes, this PR is superseded by #112 . We should close this.

**Pull request closed without merging**
