### PR TITLE
can't modprobe dm_thin_pool module

### PR DESCRIPTION
**Pull request by jaohaohsuan**
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/131)

### CODE REVIEW

**Comment by humblec** [comment]
@jaohaohsuan Thanks.. Can you please give some context about this PR wrt why this is needed ?

**Comment by jarrpa** [comment]
@jaohaohsuan The first commit doesn't give enough information on how the change relates to the subject line at all. The second commit should be its own PR, and I think is already covered by https://github.com/gluster/gluster-kubernetes/tree/master/docs/examples/hello_world

**Comment by jaohaohsuan** [comment]
Sorry about my less explanation.
I found the issue that was failed to run `glusterfs-daemonset.yaml` on `coreos`. The reason is `lvm` couldn't initial correctly.

**Comment by jaohaohsuan** [comment]
@jarrpa Feel free to omit the dynamic provisioning README.md commit.

**Pull request closed without merging**
