### PR TITLE
kargo install breaks glusterfs #1196

### PR DESCRIPTION
**Pull request by grebois**
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/347)

### CODE REVIEW

**Comment by grebois** [comment]
Workaround for https://github.com/kubernetes-incubator/kubespray/issues/1196

**Comment by jarrpa** [comment]
While I agree that the fundamental technical fix is correct, the PR is invalid. We only want to be using official upstream containers in this project, thus I am closing this PR. However, please raise an Issue here to request an updated gluster/gluster-centos image, referencing the related Issues. :)

**Comment by grebois** [comment]
@jarrpa agreed with you, will create an issue since https://github.com/gluster/gluster-containers dont have issues enabled.

**Comment by grebois** [comment]
https://github.com/gluster/gluster-kubernetes/issues/349

**Comment by jarrpa** [comment]
Thanks! I'm definitely willing to leave this PR around as a temporary workaround. :)

**Pull request closed without merging**
