### PR TITLE
use correct label to identify heketi resources

### PR DESCRIPTION
**Pull request by raghavendra-talur**
Closes: #136
Signed-off-by: Raghavendra Talur <rtalur@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/137)

### CODE REVIEW

**Comment by humblec** [comment]
Even for `deploy-heketi` this should be taken care in the same model.

**Comment by humblec** [comment]
Even `glusterfs` template should be . :)

**Comment by humblec** [comment]
Hmmm.. we have a problem. @raghavendra-talur @MohamedAshiqrh  The abort will fail in pure kube deployment.

**Comment by MohamedAshiqrh** [comment]
@humblec yeah
there are no template labels there.

**Comment by MohamedAshiqrh** [comment]
then we have to do 

${CLI} get dc,svc,routes heketi

**Comment by ramkrsna** [comment]
@raghavendra-talur  Could we make it only oc specific with  a conditional  `if [[ "${CLI}" == *oc* ]]; then  `

**Comment by raghavendra-talur** [comment]
@humblec @MohamedAshiqrh @ramkrsna sent the updated PR, please review.

**Comment by humblec** [comment]
LGTM.

**Comment by MohamedAshiqrh** [comment]
LGTM

**Pull request merged**
