### PR TITLE
vagrant: Update kubeadm join command

### PR DESCRIPTION
**Pull request by jarrpa**
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/415)

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
I think this adding this option will prevent running with older versions of k8s. Perhaps it can be conditional on the version of kubernetes? Or if we don't want to lock ourselves to version numbers maybe "scrape" the output of the help to see if our version supports that switch?

**Comment by jarrpa** [comment]
@phlogistonjohn Ah, fair point. I'll do the conditional version check.

Man, we should really move to a proper cycle of releases... ;)

**Comment by jarrpa** [comment]
@phlogistonjohn I put in a conditional check and verified that it works for latest. However, when I tried to set `kubernetes_version: 1.8.0` in `global_vars.yml` I couldn't even get to the point of testing the conditional because it failed to find any kube RPMs ending in `-1.8.0`. This leads me to ask: does setting `kubernetes_version` to anything other than latest actually work? If not, I would want this PR to merge and we can figure out a proper, broader solution later.

**Comment by phlogistonjohn** [comment]
I recently (this week) ran it with 1.8.6 when I was testing something else out. However, I did run into an additional issue using that version. Yum couldn't figure out the correct version of kubernetes-cni to use so I had to manually add kubernetes-cni-0.5.1-1.x86_64 to the install_pkgs list.

I'll leave it to you to decide if that extra hurdle means taking the PR now or deferring it.

**Comment by jarrpa** [comment]
Hmm... yeah, I'll opt to take the PR now. Without this any setups that try to use `latest` kube will not succeed.

**Comment by jarrpa** [comment]
retest this please

**Comment by jarrpa** [comment]
retest this please

**Comment by jarrpa** [comment]
Looks like there's a libvirt error in the CI. Ignoring it for now.

**Pull request merged**
