### PR TITLE
Don't add stderr to stdout when parsing `kubectl get pod` output

### PR DESCRIPTION
**Pull request by YorikSar**
Due to issue in kubectl ( kubernetes/kubernetes#48924 ) it outputs some
warnings to stderr and they are considered to be output lines and it
breaks the script in 2 places.

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/330)

### CODE REVIEW

**Comment by jarrpa** [comment]
The second change for `heketi_pod` looks like it makes sense. However, for the first one I'd as that you redirect stderr output to `/dev/null` instead. We don't care about any error messages, we'll just wait for the timeout if we don't reach a satisfactory condition.

**Comment by YorikSar** [comment]
@jarrpa  I've added that redirection.

**Comment by jarrpa** [comment]
A curiosity: Is the space between the angle bracket and the destination valid? Even so, for stylistic consistency please remove it. Yes, I'm picky. ;)

**Comment by YorikSar** [comment]
@jarrpa Yes, it's valid. Will remove...

**Comment by jarrpa** [comment]
Thanks! LGTM

**Pull request merged**
