### PR TITLE
added "--show-all" flag to stop hanging

### PR DESCRIPTION
**Pull request by mrmarcsmith**
We were experiencing a hang because of a missing flag.

Environment
Provider: Digital Ocean
Machine: Ubuntu 16.04LTS
K8s version: 
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

---
This change is [Reviewable](https://reviewable.io/reviews/gluster/gluster-kubernetes/525)

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
Interestingly, this option seems to have been removed as part of PR #502 remarking that the option has been deprecated. It also seems that someone commented on that PR saying that they hit an issue similar to the one you are describing.  (CC: @SaravanaStorageNetwork )

Regardless of that, I recommend squashing your patches together to avoid seeing the intermediate debugging steps of `set -x`.

**Comment by mrmarcsmith** [comment]
@phlogistonjohn could an admin use the "squash and merge" button?

**Comment by obnoxxx** [comment]
@mrmarcsmith writes
> @phlogistonjohn could an admin use the "squash and merge" button?

We actually disabled squash merges as it creates really bad commits. If you don't want to do the work, we can do the squashing and updating of this PR for you. But you are more than welcome to squash locally and force-push into your branch.

**Comment by obnoxxx** [comment]
I think this is actually the exact same patch as in PR #511.

**Comment by obnoxxx** [comment]
closing this as a duplicate of #511...

**Pull request closed without merging**
